alias em="emacsclient --alternate-editor='' -n$@"
alias emtty="emacsclient --alternate-editor='' -t $@"
alias emnew="emacsclient --alternate-editor='' -c -n $@"
alias ls="ls -h --color"
alias ll="ls -lv --group-directories-first"
